server {
    listen 80;
    index index.php index.html;
    server_name localhost;

    root /var/www/public; #public以外は見せない！.env,vendorとか

    location / {
        try_files $uri $uri/ /index.php$is_args$args; #静的ファイルがあればそれを返す、なければindex.phpへ。ないとLaravel ルーティング死ぬ
    }

    location ~ \.php$ { #.php ファイルだけPHP-FPM に投げる,それ以外（画像 / CSS / JS）はNginx が直接返す
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000; #Nginx → PHP の接続
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; #phpに実行すべきファイルのフルパス教えてる。
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
